# Challennge: Telecom X - Análisis de Evasión de Clientes
Se ha sido contratado como asistente de análisis de datos en Telecom X para formar parte del proyecto "Churn de Clientes". La empresa enfrenta una alta tasa de cancelaciones y necesita comprender los factores que llevan a la pérdida de clientes.

> **Desafío:** Recopilar, procesar y analizar los datos, utilizando Python y sus principales bibliotecas para extraer información valiosa. A partir de tu análisis, el equipo de Data Science podrá avanzar en modelos predictivos y desarrollar estrategias para reducir la evasión.

In [54]:
#Bibliotecas necesarias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

##📌 Extracción

In [55]:
#Cargar los datos
url_json = 'https://raw.githubusercontent.com/ingridcristh/challenge2-data-science-LATAM/refs/heads/main/TelecomX_Data.json'

In [56]:
# Convertir los datos a un DataFrame de Pandas
df = pd.read_json(url_json)

##🔧 Transformación

### Exploración de datos

In [57]:
#Exploración de datos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7267 non-null   object
 1   Churn       7267 non-null   object
 2   customer    7267 non-null   object
 3   phone       7267 non-null   object
 4   internet    7267 non-null   object
 5   account     7267 non-null   object
dtypes: object(6)
memory usage: 340.8+ KB

In [58]:
df.describe()

,customerID,Churn,customer,phone,internet,account
count,7267,7267,7267,7267,7267,7267
unique,7267,3,891,3,129,6931
top,9995-HOTOH,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'No', 'OnlineSecurity': 'N...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
freq,1,5174,223,3495,1581,6

In [59]:
df.head()

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."

### Comprobación de inconsistencias en los datos

In [60]:
#Tratmiento de los datos anidados (normalizándolos)
customer_df = pd.json_normalize(df["customer"])
phone_df = pd.json_normalize(df["phone"])
internet_df = pd.json_normalize(df["internet"])
account_df = pd.json_normalize(df["account"])

In [61]:
customer_df.head()

   gender  SeniorCitizen Partner Dependents  tenure
0  Female              0     Yes        Yes       9
1    Male              0      No         No       9
2    Male              0      No         No       4
3    Male              1     Yes         No      13
4  Female              1     Yes         No       3

In [62]:
phone_df.head()

  PhoneService MultipleLines
0          Yes            No
1          Yes           Yes
2          Yes            No
3          Yes            No
4          Yes            No

In [63]:
internet_df.head()

,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,DSL,No,Yes,No,Yes,Yes,No
1,DSL,No,No,No,No,No,Yes
2,Fiber optic,No,No,Yes,No,No,No
3,Fiber optic,No,Yes,Yes,No,Yes,Yes
4,Fiber optic,No,No,No,Yes,Yes,No

In [64]:
account_df.head()

,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,One year,Yes,Mailed check,65.6,593.3
1,Month-to-month,No,Mailed check,59.9,542.4
2,Month-to-month,Yes,Electronic check,73.9,280.85
3,Month-to-month,Yes,Electronic check,98.0,1237.85
4,Month-to-month,Yes,Mailed check,83.9,267.4

In [65]:
# Unir todo al DataFrame original
df = pd.concat(
    [df.drop(columns=["customer", "phone", "internet", "account"]),
     customer_df,
     phone_df,
     internet_df,
     account_df],
    axis=1
)

In [66]:
#Análisis del DataFrame completo
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   object
 2   gender            7267 non-null   object
 3   SeniorCitizen     7267 non-null   int64
 4   Partner           7267 non-null   object
 5   Dependents        7267 non-null   object
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   object
 8   MultipleLines     7267 non-null   object
 9   InternetService   7267 non-null   object
 10  OnlineSecurity    7267 non-null   object
 11  OnlineBackup      7267 non-null   object
 12  DeviceProtection  7267 non-null   object
 13  TechSupport       7267 non-null   object
 14  StreamingTV       7267 non-null   object
 15  StreamingMovies   7267 non-null   object
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   object
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [67]:
df.head()

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

In [68]:
df.nunique()

customerID          7267
Churn                  3
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
Charges.Monthly     1585
Charges.Total       6531
dtype: int64

In [69]:
#Verificar valores nulos
df.isnull().sum()

customerID          0
Churn               0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
Charges.Monthly     0
Charges.Total       0
dtype: int64

In [70]:
#Verificar valores duplicados
df.duplicated().sum()

np.int64(0)

In [71]:
#Error en tipos de datos incorrectos para Charges.Total
df.dtypes

customerID           object
Churn                object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
Charges.Monthly     float64
Charges.Total        object
dtype: object

In [72]:
#Error en incosistencia de datos en la columna "Churn"
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
        224
Name: count, dtype: int64

### Manejo de incosistencias

In [73]:
#Convertir a numérico, poniendo NaN
df["Charges.Total"] = pd.to_numeric(df["Charges.Total"], errors="coerce")

In [74]:
#Verificar cuantos valores NaN hay
df[df["Charges.Total"].isnull()]

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
975,1371-DWPAZ,No,Female,0,Yes,Yes,0,No,No phone service,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN
1775,2520-SGTTA,No,Female,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN
1955,2775-SEFEE,No,Male,0,No,Yes,0,Yes,Yes,DSL,...,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN
2075,2923-ARZLG,No,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN
2232,3115-CZMZD,No,Male,0,No,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN
2308,3213-VVOLG,No,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN
2930,4075-WKNIU,No,Female,0,Yes,Yes,0,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN
3134,4367-NUYAO,No,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN
3203,4472-LVYGI,No,Female,0,Yes,Yes,0,No,No phone service,DSL,...,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN
4169,5709-LVOEQ,No,Female,0,Yes,Yes,0,Yes,No,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN
5599,7644-OMVMY,No,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN

In [75]:
#Número de valores NaN
df["Charges.Total"].isnull().sum()

np.int64(11)

In [76]:
#Cambiar los valores nulos por cero
df["Charges.Total"] = df["Charges.Total"].fillna(0)

In [77]:
#Verificar nuevamento el número de valores NaN
df["Charges.Total"].isnull().sum()

np.int64(0)

In [78]:
# Verificar el valor de NaN en la columna "Churn"
df["Churn"].isnull().sum()

np.int64(0)

In [79]:
#No son NaN, por lo tanto se verifica si son strings vacíos:
(df["Churn"] == "").sum()

np.int64(224)

In [80]:
#Como son valores vacíos, no se sabe si el cliente se fue o se quedó, por lo tanto para no intentar predecir, se eliminaran esas filas para no tener información falsa
df = df[df["Churn"] != ""]

In [81]:
#Verificar que ya no haya valores vacíos
(df["Churn"] == "").sum()

np.int64(0)

In [82]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

### Creación de la columna cuentas diarias

In [83]:
#Para generar el valor por día de las cuentas se dividrá por 30 días que es el promedio de días en un mes
df["Charges.Daily"] = df["Charges.Monthly"] / 30
df["Charges.Daily"] = df["Charges.Daily"].round(2)

In [84]:
#Verificar los resultados:
df[["Charges.Monthly", "Charges.Daily"]].head()

   Charges.Monthly  Charges.Daily
0             65.6           2.19
1             59.9           2.00
2             73.9           2.46
3             98.0           3.27
4             83.9           2.80

### Estandarización y transformación de datos

In [85]:
# Renombrar las columnas para que sea más fácil de entender el DataFrame
columnas_nuevas = {
    'gender': 'Género',
    'SeniorCitizen': 'Adulto mayor',
    'Partner': 'Tiene pareja',
    'Dependents': 'Dependientes',
    'tenure': 'Meses activo',
    'PhoneService': 'Servicio telefonico',
    'MultipleLines': 'Lineas múltiples',
    'InternetService': 'Servicio de internet',
    'OnlineSecurity': 'Seguridad online',
    'OnlineBackup': 'Respaldo online',
    'DeviceProtection': 'Protección dispositivo',
    'TechSupport': 'Soporte técnico',
    'StreamingTV': 'Televisión por cable',
    'StreamingMovies': 'Streaming películas',
    'Contract': 'Tipo contrato',
    'PaperlessBilling': 'Factura digital',
    'PaymentMethod': 'Forma de pago',
    'Charges.Monthly': 'Cargo mensual',
    'Charges.Total': 'Cargo total',
    'Charges.Daily': 'Cargo diario',
    'Churn': 'Evasión'
}

# Aplicar el renombramiento
df = df.rename(columns=columnas_nuevas)
df.head()

,customerID,Evasión,Género,Adulto mayor,Tiene pareja,Dependientes,Meses activo,Servicio telefonico,Lineas múltiples,Servicio de internet,...,Protección dispositivo,Soporte técnico,Televisión por cable,Streaming películas,Tipo contrato,Factura digital,Forma de pago,Cargo mensual,Cargo total,Cargo diario
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.30,2.19
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.40,2.00
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85,2.46
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85,3.27
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.40,2.80

In [86]:
#Identificar columnas con 2 valores
df.select_dtypes(include="object").nunique()

customerID                7043
Evasión                      2
Género                       2
Tiene pareja                 2
Dependientes                 2
Servicio telefonico          2
Lineas múltiples             3
Servicio de internet         3
Seguridad online             3
Respaldo online              3
Protección dispositivo       3
Soporte técnico              3
Televisión por cable         3
Streaming películas          3
Tipo contrato                3
Factura digital              2
Forma de pago                4
dtype: int64

In [87]:
#Convertir valores textuales Yes/No en valores binarios
columnas_binarias = df.columns[df.nunique() == 2]

for col in columnas_binarias:
    if set(df[col].unique()) == {"Yes", "No"}:
        df[col] = df[col].map({"Yes": 1, "No": 0})

In [88]:
#Verificar las columnas binarias
df.head()

,customerID,Evasión,Género,Adulto mayor,Tiene pareja,Dependientes,Meses activo,Servicio telefonico,Lineas múltiples,Servicio de internet,...,Protección dispositivo,Soporte técnico,Televisión por cable,Streaming películas,Tipo contrato,Factura digital,Forma de pago,Cargo mensual,Cargo total,Cargo diario
0,0002-ORFBO,0,Female,0,1,1,9,1,No,DSL,...,No,Yes,Yes,No,One year,1,Mailed check,65.6,593.30,2.19
1,0003-MKNFE,0,Male,0,0,0,9,1,Yes,DSL,...,No,No,No,Yes,Month-to-month,0,Mailed check,59.9,542.40,2.00
2,0004-TLHLJ,1,Male,0,0,0,4,1,No,Fiber optic,...,Yes,No,No,No,Month-to-month,1,Electronic check,73.9,280.85,2.46
3,0011-IGKFF,1,Male,1,1,0,13,1,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,1,Electronic check,98.0,1237.85,3.27
4,0013-EXCHZ,1,Female,1,1,0,3,1,No,Fiber optic,...,No,Yes,Yes,No,Month-to-month,1,Mailed check,83.9,267.40,2.80

##📊 Carga y análisis

### Análisis Descriptvo

In [89]:
# Seleccionar columnas numéricas no binarias
variables_numericas = ["Meses activo", "Cargo mensual", "Cargo diario", "Cargo total"]
df[variables_numericas].describe()

       Meses activo  Cargo mensual  Cargo diario  Cargo total
count   7043.000000    7043.000000   7043.000000  7043.000000
mean      32.371149      64.761692      2.158675  2279.734304
std       24.559481      30.090047      1.003088  2266.794470
min        0.000000      18.250000      0.610000     0.000000
25%        9.000000      35.500000      1.180000   398.550000
50%       29.000000      70.350000      2.340000  1394.550000
75%       55.000000      89.850000      2.990000  3786.600000
max       72.000000     118.750000      3.960000  8684.800000

**Análisis de las variables numéricas no binarias**

In [138]:
#Media
df[variables_numericas].mean().to_frame(name="Media").round(2)

                 Media
Meses activo     32.37
Cargo mensual    64.76
Cargo diario      2.16
Cargo total    2279.73

In [139]:
#Mediana
df[variables_numericas].median().to_frame(name="Mediana").round(2)

               Mediana
Meses activo     29.00
Cargo mensual    70.35
Cargo diario      2.34
Cargo total    1394.55

In [140]:
#Desviación estándar
df[variables_numericas].std().to_frame(name="Desviación estándar").round(2)

               Desviación estándar
Meses activo                 24.56
Cargo mensual                30.09
Cargo diario                  1.00
Cargo total                2266.79

**Análisis de las variables numéricas binarias**

In [143]:
tabla_pareja_frec = df["Tiene pareja"].value_counts().to_frame("Frecuencia")
tabla_pareja_frec["Porcentaje (%)"] = (df["Tiene pareja"].value_counts(normalize=True) * 100).round(2)
tabla_pareja_frec

              Frecuencia  Porcentaje (%)
Tiene pareja
0                   3641            51.7
1                   3402            48.3

In [144]:
tabla_genero_frec = df["Género"].value_counts().to_frame("Frecuencia")
tabla_genero_frec["Porcentaje (%)"] = (df["Género"].value_counts(normalize=True) * 100).round(2)
tabla_genero_frec

        Frecuencia  Porcentaje (%)
Género
Male          3555           50.48
Female        3488           49.52

In [145]:
tabla_adulto_frec = df["Adulto mayor"].value_counts().to_frame("Frecuencia")
tabla_adulto_frec["Porcentaje (%)"] = (df["Adulto mayor"].value_counts(normalize=True) * 100).round(2)
tabla_adulto_frec

              Frecuencia  Porcentaje (%)
Adulto mayor
0                   5901           83.79
1                   1142           16.21

In [146]:
tabla_dependientes_frec = df["Dependientes"].value_counts().to_frame("Frecuencia")
tabla_dependientes_frec["Porcentaje (%)"] = (df["Dependientes"].value_counts(normalize=True) * 100).round(2)
tabla_dependientes_frec

              Frecuencia  Porcentaje (%)
Dependientes
0                   4933           70.04
1                   2110           29.96

In [147]:
tabla_serv_telefono_frec = df["Servicio telefonico"].value_counts().to_frame("Frecuencia")
tabla_serv_telefono_frec["Porcentaje (%)"] = (df["Servicio telefonico"].value_counts(normalize=True) * 100).round(2)
tabla_serv_telefono_frec

                     Frecuencia  Porcentaje (%)
Servicio telefonico
1                          6361           90.32
0                           682            9.68

**Análisis descriptivo de las variables categóricas**

In [151]:
#
tabla_contrato_frec = df["Tipo contrato"].value_counts().to_frame("Frecuencia")
tabla_contrato_frec["Porcentaje (%)"] = (tabla_contrato_frec["Frecuencia"] / tabla_contrato_frec["Frecuencia"].sum() * 100).round(2)
tabla_contrato_frec

                Frecuencia  Porcentaje (%)
Tipo contrato
Month-to-month        3875           55.02
Two year              1695           24.07
One year              1473           20.91

In [153]:
tabla_internet_frec = df["Servicio de internet"].value_counts().to_frame("Frecuencia")
tabla_internet_frec["Porcentaje (%)"] = (tabla_internet_frec["Frecuencia"] / tabla_internet_frec["Frecuencia"].sum() * 100).round(2)
tabla_internet_frec

                      Frecuencia  Porcentaje (%)
Servicio de internet
Fiber optic                 3096           43.96
DSL                         2421           34.37
No                          1526           21.67

In [154]:
tabla_soporte_frec = df["Soporte técnico"].value_counts().to_frame("Frecuencia")
tabla_soporte_frec["Porcentaje (%)"] = (tabla_soporte_frec["Frecuencia"] / tabla_soporte_frec["Frecuencia"].sum() * 100).round(2)
tabla_soporte_frec

                     Frecuencia  Porcentaje (%)
Soporte técnico
No                         3473           49.31
Yes                        2044           29.02
No internet service        1526           21.67

In [155]:
tabla_lineas_frec = df["Lineas múltiples"].value_counts().to_frame("Frecuencia")
tabla_lineas_frec["Porcentaje (%)"] = (tabla_lineas_frec["Frecuencia"] / tabla_lineas_frec["Frecuencia"].sum() * 100).round(2)
tabla_lineas_frec

                  Frecuencia  Porcentaje (%)
Lineas múltiples
No                      3390           48.13
Yes                     2971           42.18
No phone service         682            9.68

In [156]:
tabla_seguridad_frec = df["Seguridad online"].value_counts().to_frame("Frecuencia")
tabla_seguridad_frec["Porcentaje (%)"] = (tabla_seguridad_frec["Frecuencia"] / tabla_seguridad_frec["Frecuencia"].sum() * 100).round(2)
tabla_seguridad_frec

                     Frecuencia  Porcentaje (%)
Seguridad online
No                         3498           49.67
Yes                        2019           28.67
No internet service        1526           21.67

In [157]:
tabla_respaldo_frec = df["Respaldo online"].value_counts().to_frame("Frecuencia")
tabla_respaldo_frec["Porcentaje (%)"] = (tabla_respaldo_frec["Frecuencia"] / tabla_respaldo_frec["Frecuencia"].sum() * 100).round(2)
tabla_respaldo_frec

                     Frecuencia  Porcentaje (%)
Respaldo online
No                         3088           43.84
Yes                        2429           34.49
No internet service        1526           21.67

In [158]:
tabla_proteccion_frec = df["Protección dispositivo"].value_counts().to_frame("Frecuencia")
tabla_proteccion_frec["Porcentaje (%)"] = (tabla_proteccion_frec["Frecuencia"] / tabla_proteccion_frec["Frecuencia"].sum() * 100).round(2)
tabla_proteccion_frec

                        Frecuencia  Porcentaje (%)
Protección dispositivo
No                            3095           43.94
Yes                           2422           34.39
No internet service           1526           21.67

In [159]:
tabla_tv_frec = df["Televisión por cable"].value_counts().to_frame("Frecuencia")
tabla_tv_frec["Porcentaje (%)"] = (tabla_tv_frec["Frecuencia"] / tabla_tv_frec["Frecuencia"].sum() * 100).round(2)
tabla_tv_frec

                      Frecuencia  Porcentaje (%)
Televisión por cable
No                          2810           39.90
Yes                         2707           38.44
No internet service         1526           21.67

In [160]:
tabla_streaming_frec = df["Streaming películas"].value_counts().to_frame("Frecuencia")
tabla_streaming_frec["Porcentaje (%)"] = (tabla_streaming_frec["Frecuencia"] / tabla_streaming_frec["Frecuencia"].sum() * 100).round(2)
tabla_streaming_frec

                     Frecuencia  Porcentaje (%)
Streaming películas
No                         2785           39.54
Yes                        2732           38.79
No internet service        1526           21.67

### Distribución de evasión

##📄Informe final

In [107]:
# Promedios según evasión
df.groupby("Evasión")[["Meses activo", "Cargo mensual", "Cargo total"]].mean().round(2)

         Meses activo  Cargo mensual  Cargo total
Evasión
0               37.57          61.27      2549.91
1               17.98          74.44      1531.80